spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db-migrations/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password

server:
  port: 8080

jwt:
  secret-key: "2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a"
  expiration: 3600000 # 10 hours

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.sultanov: DEBUG
